-- Add name fields to users table
ALTER TABLE users
ADD COLUMN IF NOT EXISTS nombre VARCHAR(100) NULL AFTER name,
ADD COLUMN IF NOT EXISTS apellido_paterno VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS apellido_materno VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS telefono VARCHAR(20) NULL,
ADD COLUMN IF NOT EXISTS fecha_nacimiento DATE NULL;
